### ISSUE TITLE
Index New Candidate information

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/dywaj-issues#5] opened 2016-12-30 11:55 UTC
In addition to parsing and indexing the text from a candidate's CV we also need the ability to index and search additional candidate information:

**From `candidates` table:**

1) created_at
2) updated_at
3) job_type
4) industry
5) current_job_title
6) expected_salary

Also we need to be able to search based on which sectors and sector roles the candidate belongs to. See the following tables:

Candidates belong to many Sectors
Candidates belong to many Sector Roles
Sectors have many Sector Roles

- `candidate_sector_pivot`
- `candidate_sector_role_pivot`
- `sectors`
- `sector_roles`

---

From : https://bitbucket.org/Samyoul/dywaj-user-interface/issues/6/candidate-information-that-needs-to-be

created an issue 2016-06-01

**Comment by lifekent** [comment] 2017-04-12 13:42
Hi, is that the same UI as a CV search page?

**Comment by lifekent** [comment] 2017-04-13 09:43
@Samyoul I'm reviewing code and see that candidates created from the "cv" type of the "document" index (from the original CV). Candidates are saved only in the database, not in the ES as I see, right?
The question is, do you want to index candidates into separated index or add candidate additional info to its appropriate cv in the "document" index, where CVs indexed?

**Comment by Samyoul** [comment] 2017-04-16 17:36
>Hi, is that the same UI as a CV search page for having sectors and sector roles to be selected while search?

Yes that is correct.

>@Samyoul I'm reviewing code and see that candidates created from the "cv" type of the "document" index (from the original CV). Candidates are saved only in the database, not in the ES as I see, right?

Yes this is correct

>The question is, do you want to index candidates into separated index or add candidate additional info to its appropriate cv in the "document" index, where CVs indexed?

To be honest, I don't really know the best approach for this. I feel that adding this data to the pre-existing documents would be best. What would you recommend?

**Comment by lifekent** [comment] 2017-04-16 18:25
If CVs documents are persistently stored in the ES - right, adding this extra info to the document is the best choice. Furthermore, this data is pretty simple. 
Great, I'll start to work on it tomorrow.

**Comment by Samyoul** [comment] 2017-04-17 09:17
Ok, thank you.

**Comment by lifekent** [comment] 2017-04-17 14:28
@Samyoul I'm on a search phase, thinking about the current search UI and guess that these fields (job_type, industry, current_job_title) might be absolutely different for each candidate (as they are just strings in the DB and ES accordingly), and displaying all the possible values might really overload the UI, right?
How do you want me to display them?

What I'm thinking about as options:
1) Display all, perhaps it's planned to work this way.
2) Display N top results with the higher aggregated count.
3) Cool, but more time - Update these fields lists each time user select the appropriate sector. F.e. in the search UI user selects "IT" sector, below options for the "job_type" list fetched from the ES as "job_type" aggregations only for users with this particular sector or paragraph 2 if no results.

**Comment by Samyoul** [comment] 2017-04-17 14:51
>@Samyoul I'm on a search phase, thinking about the current search UI and guess that these fields (job_type, industry, current_job_title) might be absolutely different for each candidate (as they are just strings in the DB and ES accordingly), and displaying all the possible values might really overload the UI, right?
How do you want me to display them?

Yes you are right, presenting all the possible options in a select input for job_type, industry, current_job_title would be too much. It would be better to give the user blank text input field to enter keywords into. These additional input search parameters need to be hidden in the advanced search div.

> 3. Cool, but more time - Update these fields lists each time user select the appropriate sector. F.e. in the search UI user selects "IT" sector, below options for the "job_type" list fetched from the ES as "job_type" aggregations only for users with this particular sector or paragraph 2 if no results.

I like the sound of this, perhaps we could use a select2 input element so that the user can enter a custom  input string or select from a list.

**Comment by lifekent** [comment] 2017-04-17 14:59
Great, thanks for a quick reply.

**Comment by lifekent** [comment] 2017-04-18 08:14
Ready to be deployed to the dev server for testing.

Before testing we need to put right mappings for the new fields:
Download file at https://gist.github.com/lifekent/e891770fcc3961e8206c1d33a4a764ce
Run from the directory containing the downloaded file.
$ curl -XPUT "https://search-dywaj-ag6ao573vmop2gqi2id4xpjcjq.eu-west-1.es.amazonaws.com:443/document/_mapping/cv?pretty" -d @es_cv_batch_2.json

**Comment by Samyoul** [comment] 2017-04-19 10:58
Can I confirm the mapping changes will append to the pre-existing mappings and not overwrite them?

**Comment by lifekent** [comment] 2017-04-19 11:02
These are the new fields mappings, old mappings won't be changed.

**Comment by Samyoul** [comment] 2017-04-19 11:19
Ok great. I've received:

```json
{
  "acknowledged" : true
}

```

**Comment by Samyoul** [comment] 2017-04-19 11:25
Mappings now show : 

```
assumed_email - string
assumed_postcode - string
candidate_created_at - date
candidate_updated_at - date
content - string
content_checksum - string
created_at - date
current_job_title - string
cv_id - integer
expected_salary - double
file_extension - string
file_size - integer
industry - string
job_type - string
location - geo_point
original_name - string
updated_at - date
```

**Comment by lifekent** [comment] 2017-04-19 11:50
Great, thank you. I will let you know when dev is ready for testing.

**Comment by lifekent** [comment] 2017-04-20 13:06
Hi, sorry for the delay. I'm trying to figure out to test all the user cases for my updates. But looks like I'm having hard times.

### But before, some recommendations:
1) Never ever use spaces in the identifiers, like you do in the "cv" type in the ES.
2) The "assumed_email" field, which is supposed to be the relation between cv in the ES and candidate in the MySQL is indexed with the wrong mappings and can't be matched as a keyword (full email). Which means I can't relate CV with the candidate using email. Perhaps you should think about reindexing data in the right way. At least the email field.

### Delivered code:
As the email field couldn't be used as a relation, I've used an "object_key" field from the "files" table. Which is the CV id in the indexed data. That means that the candidate's info in the ES index will be indexed/updated only if the candidate has an appropriate file relation in this table. The update will be performed each time the "App\Models\User\Candidate" or "App\Models\File\File" models will be created/updated/saved.

##### I've also added an artisan command to update indexed data for the already existing candidates:
$ php artisan candidate:reindex
Let me know if you want to tweak it for running for a group of ids, date range or other conditions.

I've tried to fill candidate's profile with the sectors and sectors roles but looks like the edit page is broken http://34.252.209.137/user/edit/[:id], as well as the CV page http://34.252.209.137/candidate-cvs. For testing purposes I've added some sectors to candidates right in the db.

#### Search. Try so search some candidates, f.e. by any of this requests:
"Keyword": MMA
"Job type": Full-time, Part-time
"Current positions": Accountant, CTO
"Expected salary": f.e. from 4000 to 7000
"Industry": IT, Government
"Sectors": Accountancy and its roles

**Comment by Samyoul** [comment] 2017-04-27 15:48
Apologies for the slow reply, I've been moving home and it has taken a lot of time up.

> Never use spaces in the identifiers, like you do in the "cv" type in the ES.

Thank you. Would you be able to supply me with an example of this.

> The "assumed_email" field, which is supposed to be the relation between cv in the ES and candidate in the MySQL is indexed with the wrong mappings and can't be matched as a keyword (full email). Which means I can't relate CV with the candidate using email. Perhaps you should think about reindexing data in the right way. At least the email field.

What mapping would be appropriate? I've currently have it as `string`.

> Not sure how the Job type is filled by candidate, but make it a select from a predefined list if you didn't - you will reject duplicates like: "Full-time", "Full time" and other less meaningful like "Full day" (who knows).

Currently there are no active candidates so the Job type, so this suggestion can be implemented before users start adding data. I'll create an issue for this.

>I've tried to add initial values for the "Job type" dropdown, but...spent a few hours (didn't track of course) and... well, Select2 can't work with initial data and ajax together. Perhaps it's time to start using some real js framework, like Angular/Vue/React.

Feel free to recommend the framework you would prefer to work with and we can implement it.

>I've tried to fill candidate's profile with the sectors and sectors roles but looks like the edit page is broken http://34.252.209.137/user/edit/[:id], as well as the CV page http://34.252.209.137/candidate-cvs.

I'll create a issue for this and investigate it.

**Comment by lifekent** [comment] 2017-04-28 06:04
Hi, no worries. Congrats with moving to a new house!

Currently, CV id in the ES looks like:
"2016-04-22-14-20-48_b60717f2-ddb0-4cfd-b61c-c9b5f0baf09d_Laura Butterfield.doc"
That's not recommended to use spaces as well as special characters, dots etc.

Emails should be indexed with https://www.elastic.co/guide/en/elasticsearch/reference/1.6/analysis-uaxurlemail-tokenizer.html tokenizer, so then "example@gmail.com" indexed as a one keyword, not "example" & "gmail.com". If you decide to reindex data, think also about upgrading your ES to the latest version, 1.5 is really old. 

Regarding the JS framework, I have real experience using Angular 1.5 for a group of projects, so currently that's the only option I can work with. I have also some VueJS experiene which can be used.

I can also review/fix the issues with the candidate's edit page and CV view if you want.

**Comment by Samyoul** [comment] 2017-05-03 11:38
Hi Roman, my apologies yet again for a late reply, I'm trying to sort internet at my new place and our provider is moving very slowly, we aren't likely to get it until about 2017-05-20 . I will try to get back to you quicker though.

>Currently, CV id in the ES looks like:
"2016-04-22-14-20-48_b60717f2-ddb0-4cfd-b61c-c9b5f0baf09d_Laura Butterfield.doc"
That's not recommended to use spaces as well as special characters, dots etc.

Ah, ok yes I see what you mean. We could update the id during the re-index you suggested. We store the CV id in our database also, in `files.object_key`

>Emails should be indexed with https://www.elastic.co/guide/en/elasticsearch/reference/1.6/analysis-uaxurlemail-tokenizer.html tokenizer, so then "example@gmail.com" indexed as a one keyword, not "example" & "gmail.com". If you decide to reindex data, think also about upgrading your ES to the latest version, 1.5 is really old.

Thank you very much for this. Yes 1.5 is very old, at the time I set up these ES instances 1.5 was the only version that AWS supported, but I've noticed that AWS now supports up to version 5.1.

Are you aware of a process that could migrate the data from one index to another?

> Regarding the JS framework, I have real experience using Angular 1.5 for a group of projects, so currently that's the best option I can work with. I have also some VueJS experience which can be used.

Angular 1.5 is fine by me. Would you be available to implement the changes you feel is required to the front end? If so I will create an issue for the proposed changes.

> I can also review/fix the issues with the candidate's edit page and CV view if you want.

Yes please, proceed with this.

**Comment by lifekent** [comment] 2017-05-04 05:20
Hi, I will take a look at the edit page and CV page problems. 

Regarding the data migration, yes, I had experience moving some gigabytes of data from one ES index/host to the another, just need to check if we can move this data with to the new mappings and to the version that is so new, as I was moving data between almost the same versions (1.*, 2.*) and without any changes to the mappings. I will come back to you with the status today.

Regarding the UI, I will add Angular and work on having predefined top job titles and search for a particular sector/role.

**Comment by lifekent** [comment] 2017-05-05 15:55
I have added Angular for a frontend and also developed "Current Job Title" input to show top job titles in the dropdown on initial load. Same added for the industries dropdown.

**Comment by Samyoul** [comment] 2017-05-10 16:26
>Regarding moving data to the new ES version and index with the new mappings - successfully tested on ES 5.4, ready to go.

Do you need me to provide a new end point to migrate the data from the current ES 1.5 server?

**Comment by lifekent** [comment] 2017-05-10 16:28
Yes, need a new endpoint with the latest available ES version. I will create index with the right mappings.

**Comment by lifekent** [comment] 2017-05-10 16:29
Do the new CVs come every day?

**Comment by lifekent** [comment] 2017-05-10 16:32
Why I'm asking as it's hard to get the new data from the old index (which might be coming during migration) to a new one after moving all the current data.

**Comment by Samyoul** [comment] 2017-05-10 16:34
>Yes, need a new endpoint with the latest available ES version. I will create index with the right mappings.

Could all 3 of our indices live on the same ES 5.1 server? I'm presuming they could, so we could use search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com , the endpoint we've used for testing predictive search.

**Comment by lifekent** [comment] 2017-05-10 16:35
Sure. The third one is the "locations" index?

**Comment by Samyoul** [comment] 2017-05-10 16:37
>Do the new CVs come every day?

Currently we've put a pause on new CVs. Hopefully this will make the migration easier.

>Sure. The third one is the "locations" index?

Yes that is correct

**Comment by lifekent** [comment] 2017-05-10 16:40
Great, I will move all 3 indexes to the new endpoint with the right mappings and data. Moving CVs data might take some time. I think I will configure the dev server you provided so the data migration process should be faster than running everything on my local server. I will get back to you right after.

**Comment by Samyoul** [comment] 2017-05-10 17:05
Ok, great. Thank you.

Do you think you will need to push any more commits to https://github.com/Samyoul/dywaj-user-interface/commits/issues/5 ?

**Comment by lifekent** [comment] 2017-05-10 17:20
Yes, I would like to replace some queries since after migration we'll be able to match candidates by email in the ES index, which makes some code parts more clear and elegant.

**Comment by lifekent** [comment] 2017-05-11 05:09
@Samyoul Looks like I don't have enough permissions for the https://search-dywaj-test-pmaqcqhys4z7ncz3kooxcg7qr4.eu-west-1.es.amazonaws.com/ endpoint, can't put settings. 
You can apply them yourself, download file [settings.json](https://github.com/Samyoul/dywaj-user-interface/blob/issues/5/database/settings.json)
$ curl -XPUT "https://search-dywaj-test-pmaqcqhys4z7ncz3kooxcg7qr4.eu-west-1.es.amazonaws.com/_settings" -d @settings.json
Or give me more permissions

**Comment by lifekent** [comment] 2017-05-11 05:15
One more questions, are we going to keep current id format?

**Comment by Samyoul** [comment] 2017-05-11 15:58
The problem may be due to that (https://search-dywaj-test-pmaqcqhys4z7ncz3kooxcg7qr4.eu-west-1.es.amazonaws.com/) endpoint's version which is 1.5 . You've got full permissions on that endpoint.

I meant for this end point to be used https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/

**Comment by lifekent** [comment] 2017-05-11 16:04
Sorry, I was talking about https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com

**Comment by Samyoul** [comment] 2017-05-11 16:15
Ah, I see. I've updated your permissions on this endpoint, you should have get, post and put now.

**Comment by lifekent** [comment] 2017-05-12 07:01
Hi, but I don't have permissions to update settings, that's other permissions than the index permissions. 
Perhaps it's better for you to apply them yourself, download file [settings.json](https://github.com/Samyoul/dywaj-user-interface/blob/issues/5/database/settings.json)
$ curl -XPUT "https://search-dywaj-test-pmaqcqhys4z7ncz3kooxcg7qr4.eu-west-1.es.amazonaws.com/_settings" -d @settings.json

**Comment by Samyoul** [comment] 2017-05-12 20:06
Hi, do we need to create the index first? I've submitted this question to Stackoverflow and the response is that we need the index first and then we can make the settings:

http://stackoverflow.com/questions/43941577/error-updating-aws-elasticsearch-settings-via-command-line?noredirect=1#comment74915612_43941577

>You need to apply those settings to a specific index, so your endpoint needs to be something like `https://<index-endpoint>.es.amazonaws.com/myindex/_settings`

**Comment by lifekent** [comment] 2017-05-13 03:11
Settings can be applied globally, but, actually, I could apply them only for a document index. If we need these settings later, we will just apply them to a particular index again. 
I've updated it now, thank you and sorry for the delay.

**Comment by lifekent** [comment] 2017-05-13 03:28
I want you to make some cleanup, so I will start from scratch, want to update some naming and mapping for old settings.

$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/cv-searches?pretty"

$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/document?pretty"

$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/keywords?pretty"

There is also a ".kibana" index if that wasn't created by you, remove it too, please.
$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/.kibana?pretty"

**Comment by Samyoul** [comment] 2017-05-15 20:41
Hi I've executed the following:

```
$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/cv-searches?pretty"

$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/document?pretty"

$ curl -XDELETE "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/keywords?pretty"
```

But the .kibana index is used for analytics of all the other indexes on the endpoint, so I've left it there.

**Comment by lifekent** [comment] 2017-05-16 13:51
I have successfully transferred locations index, but having problems with the document index and cv type. The problem is that while transfer I'm getting error "ClusterBlockException", which is described in this doc http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-handling-errors.html#aes-handling-errors-yellow-index-error
I see that there is about 2 GB free space, at least according to the status of the nodes curl "https://search-dywaj-predictive-search-voksymdarvyjmq3ir2fgsm2az4.eu-west-1.es.amazonaws.com/_nodes/stats/fs?pretty=1". Can you please check if this space really available and what is the amount of memory we have. Currently transferred 732 000 and hangs with that error. Thanks

**Comment by Samyoul** [comment] 2017-05-17 14:57
Yes, the problem was that the instance had ran out of space. I've increased the space, so it should be working better now.

**Comment by lifekent** [comment] 2017-05-17 15:00
Can you please than remove the "document" and "documents" (testing) index.
It's easier and better to start from scratch.

**Comment by Samyoul** [comment] 2017-05-17 16:27
Ok, I've done this.

**Comment by lifekent** [comment] 2017-05-22 17:05
Hi, Samyoul. Sorry for the delay. Had a few really long flights on my way home to Ukraine. I will work on it tomorrow.

**Comment by Samyoul** [comment] 2017-05-22 17:59
Ok, that's fine. Thanks for letting me know.

**Comment by lifekent** [comment] 2017-05-24 19:20
Hi, I have moved the data, will push some code updates tomorrow.

**Comment by lifekent** [comment] 2017-06-02 16:37
Hi, really sorry for the delay. Didn't have time to make changes, just to remind - it works fine as it was developed before, so you can use it actually. The change I was planning to make is only a refactoring. I will try to do it asap.

**Closed** 2017-08-09 12:34 UTC
Labels: Elasticsearch, enhancement
